#!/usr/bin/env python

import argparse
import boto
import sys


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-b", "--bucket", required=True,
                        help="Bucket name")
    parser.add_argument("-k", "--key", required=True,
                        help="Key name")
    parser.add_argument("-o", "--out-file", required=True,
                        help="File name")
    args = parser.parse_args()

    conn = boto.connect_s3(anon=True)
    bucket = conn.get_bucket(args.bucket)
    key = bucket.get_key(args.key)
    if args.out_file == "-":
        key.get_contents_to_file(sys.stdout)
    else:
        key.get_contents_to_filename(args.out_file)

if __name__ == "__main__":
    main()
